import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { datadogRum } from "@datadog/browser-rum";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page}>
        <main className={styles.main}>
          <button
            onClick={() =>
              datadogRum.addAction("test", { created_at: Date.now() })
            }
          >
            Click Me!
          </button>
        </main>
      </div>
    </>
  );
}
